version: "3.9"   # Using Docker Compose spec v3.9

services:
  dind:  # This service runs Docker-in-Docker (a full Docker engine inside a container)
    image: docker:dind                       # Official Docker DinD image
    container_name: dind
    privileged: true                         # Needed so DinD can run the Docker daemon
    environment:
      - DOCKER_TLS_CERTDIR=/certs            # Enable TLS for secure communication
    volumes:
      - docker-certs-ca:/certs/ca            # Persist CA certs
      - docker-certs-client:/certs/client    # Persist client certs used by Jenkins
      - jenkins-data:/var/jenkins_home       # Share Jenkins home (optional but OK)
      - docker-data:/var/lib/docker          # Persist Docker image layers/cache in DinD
    networks:
      jenkins:
        aliases:
          - docker                           # Jenkins can reach DinD at tcp://docker:2376

  jenkins:  # Jenkins CI/CD automation server
    image: jenkins/jenkins:lts-jdk11         # LTS Jenkins with Java 11
    container_name: jenkins
    restart: unless-stopped
    user: root                                # Allow Jenkins to run docker client
    environment:
      - DOCKER_HOST=tcp://docker:2376        # Jenkins connects to DinD at this host:port
      - DOCKER_CERT_PATH=/certs/client       # Path inside Jenkins to the client certs
      - DOCKER_TLS_VERIFY=1                  # Enforce TLS verification
    ports:
      - "8080:8080"                          # Jenkins Web UI
      - "50000:50000"                        # Agent port
    volumes:
      - docker-certs-client:/certs/client:ro # Client certs as read-only
      - jenkins-data:/var/jenkins_home       # Persist jobs, plugins, config

    networks:
      - jenkins

volumes:   # Named volumes persist data even if containers are recreated
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:
  docker-data:

networks:
  jenkins:

